In [1]:
import numpy as np
import pandas as pd
import math

# Question 1

In [2]:
columns = ['label', 'message']
df = pd.read_table('./sms.tsv.txt',sep='\t', names=columns)
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.shape

(5572, 2)

In [4]:
from nltk.corpus import stopwords
stopWords = stopwords.words('english')
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [5]:
def clean_data(txt):
    lower = [word.lower() for word in txt.split()]
    
    cleaned_data = ' '.join([ps.stem(word) for word in lower if word.isalpha() and word not in stopWords])

    return cleaned_data


In [6]:
for i in range(len(df)):
    df['message'][i] = clean_data(df['message'][i])
df

label                                            message
0      ham  go jurong avail bugi n great world la e cine g...
1      ham                                      ok joke wif u
2     spam  free entri wkli comp win fa cup final tkt may ...
3      ham                        u dun say earli u c alreadi
4      ham                   nah think goe live around though
...    ...                                                ...
5567  spam            time tri contact u pound claim call per
5568   ham                                 ü b go esplanad fr
5569   ham                                               mood
5570   ham  guy bitch act like interest buy someth els nex...
5571   ham                                          true name

[5572 rows x 2 columns]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

bow = cv.fit_transform(df['message'])
print(cv.vocabulary_)
print(bow)

{'go': 1730, 'jurong': 2263, 'avail': 288, 'bugi': 575, 'great': 1790, 'world': 4838, 'la': 2342, 'cine': 765, 'got': 1760, 'amor': 136, 'ok': 2969, 'joke': 2239, 'wif': 4770, 'free': 1599, 'entri': 1332, 'wkli': 4809, 'comp': 835, 'win': 4780, 'fa': 1420, 'cup': 967, 'final': 1500, 'tkt': 4375, 'may': 2613, 'text': 4279, 'receiv': 3455, 'txt': 4499, 'appli': 192, 'dun': 1233, 'say': 3657, 'earli': 1246, 'alreadi': 118, 'nah': 2799, 'think': 4316, 'goe': 1734, 'live': 2452, 'around': 227, 'though': 4330, 'freemsg': 1604, 'hey': 1919, 'darl': 1000, 'word': 4833, 'like': 2427, 'fun': 1643, 'tb': 4239, 'xxx': 4885, 'std': 4044, 'chg': 734, 'rcv': 3432, 'even': 1366, 'brother': 554, 'speak': 3967, 'treat': 4455, 'aid': 84, 'per': 3126, 'request': 3513, 'mell': 2636, 'minnaminungint': 2680, 'nurungu': 2933, 'set': 3733, 'callertun': 622, 'press': 3288, 'copi': 895, 'friend': 1615, 'valu': 4599, 'network': 2853, 'custom': 975, 'select': 3708, 'receivea': 3456, 'prize': 3311, 'claim': 770, 'c

In [8]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()

tfidf = tfidf_transformer.fit_transform(bow)
print(tfidf)
print(tfidf.shape)

  (0, 4838)	0.2834661680965146
  (0, 2342)	0.38186323000297545
  (0, 2263)	0.40002094394580645
  (0, 1790)	0.23317532853368536
  (0, 1760)	0.18831701679530102
  (0, 1730)	0.1631994811948361
  (0, 765)	0.3439191705373717
  (0, 575)	0.35082241299257605
  (0, 288)	0.30978868489827155
  (0, 136)	0.40002094394580645
  (1, 4770)	0.5721974541660467
  (1, 2969)	0.41363998716437816
  (1, 2239)	0.708161022977506
  (2, 4809)	0.22816691435422334
  (2, 4780)	0.17597375204400065
  (2, 4499)	0.15244056303185957
  (2, 4375)	0.26440283111162705
  (2, 4279)	0.14494798837797335
  (2, 3455)	0.19500143186733102
  (2, 2613)	0.1926722277308313
  (2, 1599)	0.14289654890815606
  (2, 1500)	0.20317589950923967
  (2, 1420)	0.5625031458055175
  (2, 1332)	0.43106909152203177
  (2, 967)	0.24154051308144245
  :	:
  (5567, 4361)	0.3307113444945496
  (5567, 3253)	0.46924448848500283
  (5567, 3126)	0.4199044921210126
  (5567, 877)	0.39700745498902473
  (5567, 770)	0.3742143380838325
  (5567, 617)	0.24514806498065445
  (

In [9]:
X = np.array(tfidf.toarray())
Y = np.array(df.iloc[:, 0].values)
print(X)
print(Y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [11]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, Y_train)


MultinomialNB()

In [12]:
Y_pred = classifier.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)
cm

array([[1451,    0],
       [  71,  150]], dtype=int64)

In [14]:
accuracy = (cm[0][0] + cm[1][1]) / (cm[0][0] + cm[0][1] + cm[1][0] + cm[1][1])
accuracy

0.9575358851674641

# Question 2

In [15]:
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [16]:
iris_df = pd.DataFrame(data=np.c_[iris['data'], iris['target']], columns=iris['feature_names']+['target'])
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [17]:
iris_df['target'].unique()

array([0., 1., 2.])

In [18]:
X = iris_df.drop('target', axis=1)
Y = iris_df.iloc[:,4]
print(X)
print(Y)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
0      0.0
1      0.0
2      0.0
3      

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=22)

In [20]:
X_train = np.array(X_train)
Y_train = np.array(Y_train)
X_test = np.array(X_test)
Y_test = np.array(Y_test)

(i) Step by step implementation

In [21]:
np.unique(Y_train)

array([0., 1., 2.])

In [22]:
train_size = X_train.shape[0]
class_priors = {}
for outcome in np.unique(Y_train):
    outcome_count = sum(Y_train == outcome)
    class_priors[outcome] = outcome_count/train_size
print(class_priors)

{0.0: 0.3523809523809524, 1.0: 0.3238095238095238, 2.0: 0.3238095238095238}


In [23]:
classes = np.unique(Y_train)
classes_index = {}
subdataset = {}
for class_type in classes:
    index = []
    for i in range(len(Y_train)):
        if Y_train[i] == class_type:
            index.append(i)
    subdataset[class_type] = X_train[index, :]
subdataset[0][0]


array([5. , 3.6, 1.4, 0.2])

In [24]:
mean = {}
for class_type in classes:
    mean[class_type] = np.mean(subdataset[class_type], axis=0)
mean
    

{0.0: array([4.98918919, 3.41891892, 1.47027027, 0.23783784]),
 1.0: array([5.87941176, 2.72941176, 4.20294118, 1.31176471]),
 2.0: array([6.54117647, 2.96764706, 5.59705882, 2.04411765])}

In [25]:
stdv = {}
for class_type in classes:
    stdv[class_type] = np.std(subdataset[class_type], axis=0)
stdv

{0.0: array([0.36151616, 0.41253196, 0.18138337, 0.09109351]),
 1.0: array([0.50221826, 0.33565512, 0.49018922, 0.2111101 ]),
 2.0: array([0.65758813, 0.27623582, 0.56904734, 0.27460258])}

In [26]:
def calc_prob(X):
    prob = {}
    for class_type in classes:
        sum = 0
        for i in range(len(X)):
            sum += (-0.5*(math.log((2*math.pi)*math.pow((stdv[class_type][i]),2)))) - (math.pow((X[i] - mean[class_type][i]), 2))/(2*math.pow((stdv[class_type][i]),2))
        prob[class_type] = math.log(class_priors[class_type]) + sum
    return prob


In [27]:
Y_pred_s = np.zeros(Y_test.shape[0])
for i in range(len(X_test)):
    pred_class = None
    max_prob = -100000
    prob = calc_prob(X_test[i])
    for key, value in prob.items():
        if value > max_prob:
            max_prob = value
            pred_class = key
    Y_pred_s[i] = pred_class


(ii) Inbuilt method

In [28]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,Y_train)
Y_pred_i = gnb.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix
cm_s = confusion_matrix(Y_test, Y_pred_s)
cm_i = confusion_matrix(Y_test, Y_pred_i)
print(f'Confusion matrix for Step by step implementation:\n {cm_s}')
print(f'Confusion matrix for Inbuilt method:\n {cm_i}')


Confusion matrix for Step by step implementation:
 [[13  0  0]
 [ 0 15  1]
 [ 0  1 15]]
Confusion matrix for Inbuilt method:
 [[13  0  0]
 [ 0 15  1]
 [ 0  1 15]]


# Question 3

In [30]:
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [31]:
iris_df = pd.DataFrame(data=np.c_[iris['data'], iris['target']], columns=iris['feature_names']+['target'])
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [32]:
iris_df['target'].unique()

array([0., 1., 2.])

In [33]:
X = iris_df.drop('target', axis=1)
Y = iris_df.iloc[:,4]
print(X)
print(Y)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
0      0.0
1      0.0
2      0.0
3      

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=22)

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
knn = KNeighborsClassifier()
k_range = list(range(1, 20))
param_grid = dict(n_neighbors = k_range)

grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy', return_train_score=False)

grid_search = grid.fit(X_train, Y_train)
print(f'Best parameters: {grid_search.best_params_}')
print(f'Accuracy for taining dataset with tuning: {grid_search.best_score_*100}')

Best parameters: {'n_neighbors': 8}
Accuracy for taining dataset with tuning: 98.00000000000001


In [36]:
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=8)
knn.fit(X_train, Y_train)

Y_pred = knn.predict(X_test)

print(f'Accuracy: {accuracy_score(Y_test, Y_pred)*100}')

Accuracy: 91.11111111111111
